service: team-management
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  iam:
    role: LabRole
  iamRole: 

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'

plugins:
 - serverless-offline
 
package:
  exclude:
    - node_modules/**