service: leaderboards

provider:
  name: google
  stage: dev
  runtime: nodejs14
  region: us-central1
  project: b009040970-serverless

frameworkVersion: '3'

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  updateLeaderboard:
    handler: updateLeaderboard
    events:
      - http: POST /
  getGlobalLeaderboard:
    handler: getGlobalLeaderboard
    events:
      - http: GET /
  filterLeaderboardByTimeFrame:
    handler: filterLeaderboardByTimeFrame
    events:
      - http: GET /
  getEntityStatistics:
    handler: getEntityStatistics
    events:
      - http: GET /
  getLeaderboardByEntityId:
    handler: getLeaderboardByEntityId
    events:
      - http: GET /