service: game-experience
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sns:*'
        - 'sqs:*'
      Resource: '*'
  role: arn:aws:iam::041159192901:role/LabRole

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    ChatSNSTopic:
      Type: 'AWS::SNS::Topic'
      Properties:
        TopicName: 'ChatTopic'
    ChatSQSQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'ChatQueue'
    SnsSubscription:
      Type: 'AWS::SNS::Subscription'
      Properties:
        TopicArn: 
          Ref: 'ChatSNSTopic'
        Protocol: 'sqs'
        Endpoint: 
          Fn::GetAtt: 
            - ChatSQSQueue
            - Arn
    ChatQueuePolicy:
      Type: 'AWS::SQS::QueuePolicy'
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Principal: '*'
              Action: 'SQS:SendMessage'
              Resource: 
                Fn::GetAtt:
                  - ChatSQSQueue
                  - Arn
              Condition:
                ArnEquals:
                  'aws:SourceArn': 
                    Ref: 'ChatSNSTopic'
        Queues:
          - "https://sqs.us-east-1.amazonaws.com/041159192901/ChatQueue"
